const Exception = () => {};

export default Exception;
